### PR TITLE
Update SCI to new org

### PR DESCRIPTION
**Pull request by borkdude**

### CODE REVIEW

**Comment by liquidz** [comment]
Thanks!

**Comment by borkdude** [comment]
It seems the older `borkdude/sci` is still being pulled in via babashka.nrepl... I will provide an update for that too. For now you can put an `:exclusions` on that dependency and that should fix CI. Maybe enable running tests on PRs too?

**Comment by borkdude** [comment]
https://github.com/liquidz/dad/pull/26

**Comment by liquidz** [comment]
@borkdude 
Currently, I'm making major changes (mainly for supporting pods) in the dev branch, so I'll fix CI there :)

**Comment by borkdude** [comment]
@liquidz Thanks! It would still be good to merge #26 as this avoids bringing in `borkdude/sci` which causes problems in combination with `org.babashka/sci`.

**Pull request merged**
